# username/repository
id: usac-fe-docs
# name of the software
name: USA Cycling Frontend Docs
# current version of the software
version: 0.0.1
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT
# extension of the favicon, blank to disable
favicon: png

# download button
# if download.popup is true, the download button will open a popup with several download options
# otherwise it will simply open download.url and other options are ignored
# if download.popup is true, any option is optional
# download.cdn.img is optional
download:
  enable: false
  popup: false
  url: https://github.com/mistic100/jekyll-bootstrap-doc/archive/gh-pages.zip
  bower: jekyll-bootstrap-doc
  npm: jekyll-bootstrap-doc
  cdn:
    url: https://cdnjs.com/libraries/jekyll-bootstrap-doc
    img: https://alemangui.github.io/pizzicato/img/cdnjs.svg
    name: cdnjs

# set this to true to replace the generated header navbar by _includes/navbar.html
customNavBar: false

# list of additional links on the right of the top menu
headerLinks:
  - title: Source
    url: https://github.com/bowtie-co/jekyll-bootstrap-doc
  - title: Author
    url: https://bowtie.co

# list if additional links on the footer
footerLinks:
  - title: Source
    url: https://github.com/bowtie-co/jekyll-bootstrap-doc
  - title: Issues
    url: https://github.com/bowtie-co/jekyll-bootstrap-doc/issues?state=open

# header
header:
  color1: "#181d49"
  color2: "#003d6e"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: bowtie-co
  repo: jekyll-bootstrap-doc

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: true
  profileUrl:


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
